### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by MARIA2M** [MARIA2M/testsim#1]
Hola Tomás,

Te escribo porque no sabía si irías mirando estos días los repositorios o teníamos que avisarte. Yo lo terminé el viernes y me gustaría que me notificaras cuando tengas un momento las posibles correcciones que pueda tener el proyecto. 

Muchas gracias y un saludo.

María

**Comment by tdido** [comment]
Hola María.

El script está muy bien. Los comentarios son un buen detalle adicional, queda muy claro todo.

El único comentario es que la creación del ambiente conda no es necesario hacerla dentro del script, ya que la creación y modificación del ambiente se hacen a mano y nada dentro del script las modifica. Quizá no quedó claro en las instrucciones, pero la idea era hacerlo manualmente una única vez.

Cierro la issue para indicar que el trabajo está terminado correctamente.
